-- Add Pixel War fields to Checkin model
ALTER TABLE "Checkin" ADD COLUMN "color" TEXT NOT NULL DEFAULT '#818cf8';
ALTER TABLE "Checkin" ADD COLUMN "pixelLat" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Checkin" ADD COLUMN "pixelLng" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Checkin" ADD COLUMN "level" TEXT NOT NULL DEFAULT 'pixel';
ALTER TABLE "Checkin" ADD COLUMN "placeId" TEXT;
